# Generated by Django 5.1 on 2025-01-03 10:18

import carts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discount_type', models.CharField(choices=[('PRODUCT', 'تخفیف محصول'), ('COUPON', 'کد تخفیف')], max_length=10)),
                ('discount_percent', models.IntegerField(validators=[carts.validators.validate_discount_percent, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[carts.validators.validate_promotion_code])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(validators=[carts.validators.validate_future_date])),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[carts.validators.validate_positive_number])),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
